
basepath = '/storage/home/gunes/palm/my.model.git/build/JOBS/my_carmine_prague/OUTPUT'
origpath = basepath
finalpath = os.path.join(basepath, 'JOINED')

filelist = [
    'my_carmine_prague_ts',
    'my_carmine_prague_xy'
]


#filelist = [
#    'my_carmine_prague_av_surf',
#    'my_carmine_prague_av_xy',
#    'my_carmine_prague_pr',
#    'my_carmine_prague_surf',
#    'my_carmine_prague_topo_surf',
#    'my_carmine_prague_ts',
#    'my_carmine_prague_xy'
#]

convention = 'filenum'
file_suffix = '.nc'

